name: Build & Deploy Microservices

on:
  push:
    branches:
      - main

jobs:
  build-deploy:
    name: Build and Deploy Microservices
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Required for fetching all history for tj-actions/changed-files

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'microsoft'
          java-version: '17'
          cache: 'maven'

      - name: Get changed services
        id: changed-services
        uses: tj-actions/changed-files@v41
        with:
          files: services/**
          dir_names: true
          dir_names_max_depth: 2

      - name: Build and Test All Services
        run: mvn clean install

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker images for changed services
        run: |
          for service in ${{ steps.changed-services.outputs.all_changed_files }}; do
            service_name=$(basename "$service")
            echo "Building and pushing Docker image for $service_name"
            docker build -t ${{ secrets.DOCKER_USERNAME }}/$service_name:latest $service
            docker push ${{ secrets.DOCKER_USERNAME }}/$service_name:latest
          done